spring.application.name=springapi

#Port configuration
#port on which our application will be running
# server.port=8080

#DB configuration
#here studentsDB is our DB name
spring.datasource.url=jdbc:mysql://localhost:3306/studentsDB?createDatabaseIfNotExist=true&serverTimezone=UTC
#username given while installing mysql
spring.datasource.username=root
#password specified while installing mysql
spring.datasource.password=mysqlS@1806
#This will create schema on running your application and will also drop all schemas once you stop your application
spring.jpa.hibernate.ddl-auto=update
#TO see all the sql statements runned by hibernate
spring.jpa.show-sql=true
#Format the hibernate queries, statements
spring.jpa.properties.hibernate.format_sql=true

# For Spring Boot 3.x / Hibernate 6+
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# OR if you want to be very specific for MySQL 8
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
